"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AvatarPairAnimation } from "@/components/screens/AvatarPairAnimation";
import { fadeUpStagger, fadeUpItem } from "@/lib/animations";
import type { Profile } from "@/lib/store";

interface Props {
  profile: Profile;
  onMessage: () => void;
  onKeepLurching: () => void;
}

const CHECK_SVG = (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
    <path d="M2.5 7L5.5 10L11.5 4" stroke="#4A7C59" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export function MatchOverlay({ profile, onMessage, onKeepLurching }: Props) {
  const [statsVisible, setStatsVisible] = useState(false);

  const stats = [
    { label: "Wound Compatibility", value: "74%" },
    { label: "Attachment Dynamic", value: "Anxious x Avoidant" },
    { label: "Estimated Duration", value: "6-8 weeks" },
    { label: "Ghost Probability", value: `${profile.ghostRisk}%` },
    { label: "Therapy Bills Projected", value: "48,000" },
  ];

  return (
    <div style={{
      background: "#1A1612",
      border: "1px solid #3A2E24",
      padding: "28px 24px 24px",
      display: "flex",
      flexDirection: "column",
      gap: "20px",
    }}>
      {/* Avatars */}
      <div style={{ display: "flex", justifyContent: "center" }}>
        <AvatarPairAnimation
          userAvatarColor="#8B1A1A"
          matchAvatarColor={profile.photoColor}
          matchName={profile.name}
          onAnimationComplete={() => setStatsVisible(true)}
        />
      </div>

      {/* Heading */}
      <div style={{ textAlign: "center" }}>
        <p style={{
          fontFamily: "var(--font-display)", fontSize: "10px",
          textTransform: "uppercase", letterSpacing: "0.18em",
          color: "#8B1A1A", marginBottom: "8px",
        }}>
          It&apos;s a Lurch
        </p>
        <h2 style={{
          fontFamily: "var(--font-display)", fontSize: "34px",
          fontWeight: 600, lineHeight: 1.1, color: "#F0EDED",
          marginBottom: "8px",
        }}>
          You matched.
        </h2>
        <p style={{
          fontFamily: "var(--font-ui)", fontSize: "14px", fontStyle: "italic",
          color: "#AEADAD", lineHeight: 1.5,
        }}>
          You and {profile.name.charAt(0) + profile.name.slice(1).toLowerCase()} have compatible damage.
        </p>
      </div>

      {/* Stats card */}
      <AnimatePresence>
        {statsVisible && (
          <motion.div
            variants={fadeUpStagger}
            initial="initial"
            animate="animate"
            style={{
              background: "#231E18",
              borderRadius: "14px",
              overflow: "hidden",
            }}
          >
            {stats.map(({ label, value }, i) => (
              <motion.div
                key={label}
                variants={fadeUpItem}
                style={{
                  display: "flex", alignItems: "center",
                  justifyContent: "space-between",
                  padding: "11px 16px",
                  borderBottom: i < stats.length - 1 ? "1px solid rgba(255,255,255,0.08)" : "none",
                }}
              >
                <span style={{ fontFamily: "var(--font-ui)", fontSize: "12px", color: "#8A8070" }}>
                  {label}
                </span>
                <span style={{ fontFamily: "var(--font-display)", fontSize: "13px", fontWeight: 600, color: "#EDE8DF" }}>
                  {value}
                </span>
              </motion.div>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Disclaimer */}
      <p style={{
        fontFamily: "var(--font-ui)", fontSize: "11px", fontStyle: "italic",
        color: "#AEADAD", lineHeight: 1.5, textAlign: "center",
      }}>
        These numbers were generated by an algorithm. They will feel true.
      </p>

      {/* CTA */}
      <button
        onClick={onMessage}
        style={{
          display: "block", width: "100%", height: "44px",
          background: "#8B1A1A", borderRadius: "14px",
          fontFamily: "var(--font-display)", fontSize: "15px",
          fontWeight: 600, color: "#EAE6E6", textAlign: "center",
        }}
      >
        Send a message
      </button>

      {/* Ghost */}
      <button
        onClick={onKeepLurching}
        style={{
          display: "block", width: "100%", textAlign: "center",
          fontFamily: "var(--font-ui)", fontSize: "11px",
          fontStyle: "italic", fontWeight: 500, color: "#AEADAD",
          marginTop: "-8px",
        }}
      >
        keep lurching
      </button>
    </div>
  );
}
