"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ScreenWrapper } from "@/components/layout/ScreenWrapper";
import { ScoreCountUp } from "@/components/indicators/ScoreCountUp";
import { DividerLine } from "@/components/indicators/DividerLine";
import { WarmNote } from "@/components/screens/WarmNote";
import { CTAButton } from "@/components/inputs/CTAButton";
import { useLurchStore } from "@/lib/store";

export default function ScorePage() {
  const router = useRouter();
  const { woundDepth, ghostRisk, patternRepeat, readiness, setTransitionDirection } = useLurchStore();
  const [scoresComplete, setScoresComplete] = useState(false);
  const [dividerComplete, setDividerComplete] = useState(false);
  const [scoreCount, setScoreCount] = useState(0);

  const handleScoreComplete = () => {
    setScoreCount((c) => {
      const next = c + 1;
      if (next >= 4) setScoresComplete(true);
      return next;
    });
  };

  const handleContinue = () => {
    setTransitionDirection("up");
    router.push("/feed");
  };

  return (
    <ScreenWrapper>
      <div
        className="h-full flex flex-col overflow-y-auto lurch-scroll"
        style={{
          padding: "calc(env(safe-area-inset-top, 0px) + 40px) 40px calc(env(safe-area-inset-bottom, 0px) + 32px)",
          background: "#0F0D0B",
        }}
      >
        {/* Eyebrow */}
        <p
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "11px",
            textTransform: "uppercase",
            letterSpacing: "0.12em",
            color: "#AEADAD",
            marginBottom: "24px",
          }}
        >
          YOUR DAMAGE PROFILE
        </p>

        {/* Stats card — brief: distinct bg, 1px border, 24px internal padding */}
        <div
          style={{
            background: "#1A1612",
            border: "1px solid #2E2720",
            borderRadius: "16px",
            padding: "0 24px",
            marginBottom: "32px",
          }}
        >
          <ScoreCountUp
            label="Wound Depth"
            target={woundDepth ?? 73}
            suffix="/100"
            delayMs={200}
            format="integer"
            onComplete={handleScoreComplete}
          />
          <ScoreCountUp
            label="Ghost Risk (you)"
            target={ghostRisk ?? 41}
            delayMs={800}
            format="percent"
            onComplete={handleScoreComplete}
          />
          <ScoreCountUp
            label="Pattern Repeat Index"
            target={patternRepeat ?? 4.2}
            suffix="x"
            delayMs={1400}
            format="decimal"
            onComplete={handleScoreComplete}
          />
          <ScoreCountUp
            label="Readiness for Real Intimacy"
            target={readiness ?? 31}
            delayMs={2000}
            format="percent"
            onComplete={handleScoreComplete}
            isLast
          />
          {/* Footnote inside card */}
          <p
            style={{
              fontFamily: "var(--font-ui)",
              fontSize: "12px",
              fontStyle: "italic",
              lineHeight: "1.6",
              color: "#AEADAD",
              borderTop: "1px solid #2E2720",
              padding: "14px 0",
            }}
          >
            Scores generated by an algorithm that knows nothing about you.
          </p>
        </div>

        {/* brief: accent divider signals tonal shift before emotional copy */}
        {scoresComplete && (
          <DividerLine
            accent
            className="mb-8"
            onComplete={() => setDividerComplete(true)}
          />
        )}

        <WarmNote visible={dividerComplete} />

        {dividerComplete && (
          <div style={{ marginTop: "32px" }}>
            <CTAButton onClick={handleContinue}>ENTER THE APP</CTAButton>
          </div>
        )}
      </div>
    </ScreenWrapper>
  );
}
